# Common configuration.

AllCops:
  TargetRubyVersion: 2.5
Metrics/LineLength:
  Max: 120
Style/EmptyCaseCondition:
  Enabled: false
Layout/FirstParameterIndentation:
  Enabled: false
Layout/IndentArray:
  Enabled: false
Layout/MultilineBlockLayout:
    Enabled: false
Layoout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
